name: ${project.name}
version: ${project.version}

main: me.remag501.adventure.AdventurePlugin
api-version: '1.21'

commands:
  adventure:
    description: Teleport to the current adventure world
    usage: /adventure

depend:
  - BGSCore
  - Multiverse-Core
  - BetterRTP
  - PlaceholderAPI